export interface LeetCodeBadgeItem {
  id: string;
  title: string;
  category: 'Submission Streak' | 'Annual Milestone' | 'Competition Medal' | 'Daily Coding Challenge';
  date: string;
  gifPath: string;
  spritePath: string;
  description: string;
  tierColor: 'amber' | 'emerald' | 'blue' | 'purple' | 'cyan' | 'rose' | 'orange';
}

export const leetcodeBadgesData: LeetCodeBadgeItem[] = [
  // --- Submission Streak Badges ---
  {
    id: '500-days-streak',
    title: '500 Days Badge',
    category: 'Submission Streak',
    date: '2026-09-01',
    gifPath: '/images/badges/500-days-badge-all.gif',
    spritePath: '/images/badges/sprites/500-days-badge-all.webp',
    description: 'Awarded for completing daily coding challenges across 500 distinct days of algorithmic problem solving.',
    tierColor: 'emerald',
  },
  {
    id: '365-days-streak',
    title: '365 Days Badge',
    category: 'Submission Streak',
    date: '2026-04-10',
    gifPath: '/images/badges/365-days-badge-all.gif',
    spritePath: '/images/badges/sprites/365-days-badge-all.webp',
    description: 'Awarded for completing 365 consecutive days of active LeetCode daily problem solving.',
    tierColor: 'amber',
  },

  // --- Annual Medals ---
  {
    id: '200-days-2026',
    title: '200 Days Badge 2026',
    category: 'Annual Milestone',
    date: '2026-07-29',
    gifPath: '/images/badges/200-days-badge-2026.gif',
    spritePath: '/images/badges/sprites/200-days-badge-2026.webp',
    description: 'Achieved 200 days of verified daily problem submissions during the 2026 calendar year.',
    tierColor: 'purple',
  },
  {
    id: '100-days-2026',
    title: '100 Days Badge 2026',
    category: 'Annual Milestone',
    date: '2026-04-16',
    gifPath: '/images/badges/100-days-badge-2026.gif',
    spritePath: '/images/badges/sprites/100-days-badge-2026.webp',
    description: 'Achieved 100 days of verified daily problem submissions during the 2026 calendar year.',
    tierColor: 'blue',
  },
  {
    id: '50-days-2026',
    title: '50 Days Badge 2026',
    category: 'Annual Milestone',
    date: '2026-02-21',
    gifPath: '/images/badges/50-days-badge-2026.gif',
    spritePath: '/images/badges/sprites/50-days-badge-2026.webp',
    description: 'Achieved 50 days of verified daily problem submissions during the 2026 calendar year.',
    tierColor: 'cyan',
  },
  {
    id: '200-days-2025',
    title: '200 Days Badge 2025',
    category: 'Annual Milestone',
    date: '2025 (Active)',
    gifPath: '/images/badges/200-days-badge-2025.gif',
    spritePath: '/images/badges/sprites/200-days-badge-2025.webp',
    description: 'Achieved 200 days of verified daily problem submissions during the 2025 calendar year.',
    tierColor: 'purple',
  },
  {
    id: '100-days-2025',
    title: '100 Days Badge 2025',
    category: 'Annual Milestone',
    date: '2025-07-16',
    gifPath: '/images/badges/100-days-badge-2025.gif',
    spritePath: '/images/badges/sprites/100-days-badge-2025.webp',
    description: 'Achieved 100 days of verified daily problem submissions during the 2025 calendar year.',
    tierColor: 'blue',
  },
  {
    id: '50-days-2025',
    title: '50 Days Badge 2025',
    category: 'Annual Milestone',
    date: '2025-05-25',
    gifPath: '/images/badges/50-days-badge-2025.gif',
    spritePath: '/images/badges/sprites/50-days-badge-2025.webp',
    description: 'Achieved 50 days of verified daily problem submissions during the 2025 calendar year.',
    tierColor: 'cyan',
  },

  // --- Competition / Quest Medals ---
  {
    id: 'data-navigator',
    title: 'Data Navigator Badge',
    category: 'Competition Medal',
    date: '2026-01-26',
    gifPath: '/images/badges/data-navigator-badge.gif',
    spritePath: '/images/badges/sprites/data-navigator-badge.webp',
    description: 'Specialized competitive quest mastery in data structuring, tree manipulations, and graph traversals.',
    tierColor: 'emerald',
  },
  {
    id: 'mathematical-insight',
    title: 'Mathematical Insight Badge',
    category: 'Competition Medal',
    date: '2026-01-25',
    gifPath: '/images/badges/mathematical-insight-badge.gif',
    spritePath: '/images/badges/sprites/mathematical-insight-badge.webp',
    description: 'Specialized competitive quest mastery in combinatorics, modular arithmetic, and numerical reasoning.',
    tierColor: 'orange',
  },

  // --- Daily Coding Challenges (2026 & 2025) ---
  {
    id: 'dcc-august-2026',
    title: 'Aug LeetCoding Challenge',
    category: 'Daily Coding Challenge',
    date: '2026-09-01',
    gifPath: '/images/badges/dcc-august-2026.gif',
    spritePath: '/images/badges/sprites/dcc-august-2026.webp',
    description: 'Completed 100% of daily challenge problems for August 2026.',
    tierColor: 'rose',
  },
  {
    id: 'dcc-july-2026',
    title: 'Jul LeetCoding Challenge',
    category: 'Daily Coding Challenge',
    date: '2026-08-01',
    gifPath: '/images/badges/dcc-july-2026.gif',
    spritePath: '/images/badges/sprites/dcc-july-2026.webp',
    description: 'Completed 100% of daily challenge problems for July 2026.',
    tierColor: 'rose',
  },
  {
    id: 'dcc-june-2026',
    title: 'Jun LeetCoding Challenge',
    category: 'Daily Coding Challenge',
    date: '2026-06-30',
    gifPath: '/images/badges/dcc-june-2026.gif',
    spritePath: '/images/badges/sprites/dcc-june-2026.webp',
    description: 'Completed 100% of daily challenge problems for June 2026.',
    tierColor: 'amber',
  },
  {
    id: 'dcc-may-2026',
    title: 'May LeetCoding Challenge',
    category: 'Daily Coding Challenge',
    date: '2026-05-31',
    gifPath: '/images/badges/dcc-may-2026.gif',
    spritePath: '/images/badges/sprites/dcc-may-2026.webp',
    description: 'Completed 100% of daily challenge problems for May 2026.',
    tierColor: 'amber',
  },
  {
    id: 'dcc-april-2026',
    title: 'Apr LeetCoding Challenge',
    category: 'Daily Coding Challenge',
    date: '2026-04-30',
    gifPath: '/images/badges/dcc-april-2026.gif',
    spritePath: '/images/badges/sprites/dcc-april-2026.webp',
    description: 'Completed 100% of daily challenge problems for April 2026.',
    tierColor: 'amber',
  },
  {
    id: 'dcc-march-2026',
    title: 'Mar LeetCoding Challenge',
    category: 'Daily Coding Challenge',
    date: '2026-03-31',
    gifPath: '/images/badges/dcc-march-2026.gif',
    spritePath: '/images/badges/sprites/dcc-march-2026.webp',
    description: 'Completed 100% of daily challenge problems for March 2026.',
    tierColor: 'emerald',
  },
  {
    id: 'dcc-february-2026',
    title: 'Feb LeetCoding Challenge',
    category: 'Daily Coding Challenge',
    date: '2026-02-28',
    gifPath: '/images/badges/dcc-february-2026.gif',
    spritePath: '/images/badges/sprites/dcc-february-2026.webp',
    description: 'Completed 100% of daily challenge problems for February 2026.',
    tierColor: 'cyan',
  },
  {
    id: 'dcc-january-2026',
    title: 'Jan LeetCoding Challenge',
    category: 'Daily Coding Challenge',
    date: '2026-01-31',
    gifPath: '/images/badges/dcc-january-2026.gif',
    spritePath: '/images/badges/sprites/dcc-january-2026.webp',
    description: 'Completed 100% of daily challenge problems for January 2026.',
    tierColor: 'blue',
  },
  {
    id: 'dcc-december-2025',
    title: 'Dec LeetCoding Challenge',
    category: 'Daily Coding Challenge',
    date: '2025-12-31',
    gifPath: '/images/badges/dcc-december-2025.gif',
    spritePath: '/images/badges/sprites/dcc-december-2025.webp',
    description: 'Completed 100% of daily challenge problems for December 2025.',
    tierColor: 'purple',
  },
  {
    id: 'dcc-november-2025',
    title: 'Nov LeetCoding Challenge',
    category: 'Daily Coding Challenge',
    date: '2025-11-30',
    gifPath: '/images/badges/dcc-november-2025.gif',
    spritePath: '/images/badges/sprites/dcc-november-2025.webp',
    description: 'Completed 100% of daily challenge problems for November 2025.',
    tierColor: 'rose',
  },
  {
    id: 'dcc-october-2025',
    title: 'Oct LeetCoding Challenge',
    category: 'Daily Coding Challenge',
    date: '2025-10-31',
    gifPath: '/images/badges/dcc-october-2025.gif',
    spritePath: '/images/badges/sprites/dcc-october-2025.webp',
    description: 'Completed 100% of daily challenge problems for October 2025.',
    tierColor: 'rose',
  },
  {
    id: 'dcc-september-2025',
    title: 'Sep LeetCoding Challenge',
    category: 'Daily Coding Challenge',
    date: '2025-09-30',
    gifPath: '/images/badges/dcc-september-2025.gif',
    spritePath: '/images/badges/sprites/dcc-september-2025.webp',
    description: 'Completed 100% of daily challenge problems for September 2025.',
    tierColor: 'rose',
  },
  {
    id: 'dcc-august-2025',
    title: 'Aug LeetCoding Challenge',
    category: 'Daily Coding Challenge',
    date: '2025-08-31',
    gifPath: '/images/badges/dcc-august-2025.gif',
    spritePath: '/images/badges/sprites/dcc-august-2025.webp',
    description: 'Completed 100% of daily challenge problems for August 2025.',
    tierColor: 'orange',
  },
  {
    id: 'dcc-july-2025',
    title: 'Jul LeetCoding Challenge',
    category: 'Daily Coding Challenge',
    date: '2025-07-31',
    gifPath: '/images/badges/dcc-july-2025.gif',
    spritePath: '/images/badges/sprites/dcc-july-2025.webp',
    description: 'Completed 100% of daily challenge problems for July 2025.',
    tierColor: 'amber',
  },
  {
    id: 'dcc-june-2025',
    title: 'Jun LeetCoding Challenge',
    category: 'Daily Coding Challenge',
    date: '2025-06-30',
    gifPath: '/images/badges/dcc-june-2025.gif',
    spritePath: '/images/badges/sprites/dcc-june-2025.webp',
    description: 'Completed 100% of daily challenge problems for June 2025.',
    tierColor: 'amber',
  },
  {
    id: 'dcc-may-2025',
    title: 'May LeetCoding Challenge',
    category: 'Daily Coding Challenge',
    date: '2025-06-01',
    gifPath: '/images/badges/dcc-may-2025.gif',
    spritePath: '/images/badges/sprites/dcc-may-2025.webp',
    description: 'Completed 100% of daily challenge problems for May 2025.',
    tierColor: 'amber',
  },
  {
    id: 'dcc-april-2025',
    title: 'Apr LeetCoding Challenge',
    category: 'Daily Coding Challenge',
    date: '2025-06-01',
    gifPath: '/images/badges/dcc-april-2025.gif',
    spritePath: '/images/badges/sprites/dcc-april-2025.webp',
    description: 'Completed 100% of daily challenge problems for April 2025.',
    tierColor: 'emerald',
  },
];
